 datasource:
   url: jdbc:postgresql://localhost:5432/team_management
   username: postgres
   password: postgres
   driverClassName: org.postgresql.Driver
   default_schema: public
   
 hibernate:
   dialect: org.hibernate.dialect.PostgreSQLDialect
   packagesToScan: br.com.mamr.teammanagement.domain
   show_sql: true
   hbm2ddl:
      auto: create
    
           